Creating Dapr-Enabled developer environments using Kratix
dapr/blog pull request #102
Opened 2023-03-29 14:51 UTC by salaboy

This blog post shows how to use Kratix.io and Dapr together to enable platform teams to create Dapr-enabled Development environments. The blog post links to a step-by-step tutorial to get this working on your local environment using Kubernetes KinD.

2023-03-30 08:56 UTC, marcduiker requested changes

2023-03-30 08:56 UTC, marcduiker commented on daprblog/content/posts/2023/dapr-kratix/dapr-kratix-01.png
The `Kubernetes Cluster` text is hidden by the Platform and Environment blocks. Can you fix this?

2023-03-30 08:56 UTC, marcduiker commented on daprblog/content/posts/2023/dapr-kratix/index.md
> +With this environment definition, we can request our platform to creates a new development environment, with the applications that we want to modify deployed and with a database provisioned specifica
```suggestion
With this environment definition, we can request our platform to create a new development environment, with the applications that we want to modify deployed and with a database provisioned specifically for these environments (in contrast with connecting to an existing database). 
```

2023-03-30 08:56 UTC, marcduiker commented on daprblog/content/posts/2023/dapr-kratix/index.md
> +Check the latest [Dapr 1.10 release](https://github.com/dapr/dapr/releases/tag/v1.10.0) contains many new features and improvements, such as Workflow, Pluggable Component SDKs, and Multi-App Run, rea
```suggestion
Check the latest [Dapr 1.10 release](https://github.com/dapr/dapr/releases/tag/v1.10.0) contains many new features and improvements, such as Workflow, Pluggable Component SDKs, and Multi-App Run, read all about them in [this blog post](https://www.diagrid.io/blog/dapr-1-10-release-highlights). Check out the [GitHub repository](https://github.com/salaboy/from-monolith-to-k8s/platform/) for more examples, and feel free to reach out if you have questions via [Twitter @Salaboy](https://twitter.com/salaboy) or my blog [https://salaboy.com](https://www.salaboy.com). You are welcome to join the [Dapr Discord](http://bit.ly/dapr-discord) and check the [Kratix Community Page](https://kratix.io/docs/main/community) to share your experience with both Dapr and Kratix.
```

2023-03-30 08:56 UTC, marcduiker commented on daprblog/content/posts/2023/dapr-kratix/index.md
> +For this to work, the promise definition needs to include a reference to our **Environment CRD**, to the [Dapr]() and [Redis]() Promise coming from the Marketplace, and to a Pipeline that will glue t
No links for Dapr and Redis Promises?

2023-03-30 08:56 UTC, marcduiker commented on daprblog/content/posts/2023/dapr-kratix/index.md
> +For this simple example, we will deploy two applications, one that writes data to the statestore and one that reads data from the statestore. The application that writes data into the statestore is w
```suggestion
For this small example, we will deploy two applications, one that writes data to the statestore and one that reads data from the statestore. The application that writes data into the statestore is written in Java and the application that reads from the statestore is written in Go. For this small application we have used the Dapr SDKs (Java and Go), but the same behaviour can be implemented using plain HTTP or GRPC calls to the Dapr Sidecar that gets injected when we deploy these applications. 
```

2023-03-30 08:56 UTC, marcduiker commented on daprblog/content/posts/2023/dapr-kratix/index.md
> +* Scheduling hints that determine to which worker cluster each Promise is scheduled. For example, users can request Promises are sent to their own dev cluster through a simple label and selector patt
```suggestion
* Scheduling hints that determine to which worker cluster each Promise is scheduled. For example, users can request Promises are sent to their own dev cluster through a label and selector pattern. Kratix also supports more complex scheduling patterns. i.e platform operators can determine that all clusters are given a certain set of Promises (security, billing, observability).  
```

2023-03-30 08:56 UTC, marcduiker commented on daprblog/content/posts/2023/dapr-kratix/index.md
> +Our Environment CRD is quite simple, but in real life, this should contain all the parameters that development teams can tweak when creating requests to our platform.
```suggestion
Our Environment CRD is quite basic, but in real life, this should contain all the parameters that development teams can tweak when creating requests to our platform. 
```

2023-03-30 08:56 UTC, marcduiker commented on daprblog/content/posts/2023/dapr-kratix/index.md
> +In this short blog post, we have enabled the platform team(s) to define an Environment Promise that application teams can request on demand. We have used two existing Kratix Promises to compose a hig
```suggestion
In this short blog post, we have enabled the platform team(s) to define an Environment Promise that application teams can request on demand. We have used two existing Kratix Promises to compose a higher-level Promise that our basic Environment resource can expose. While Kratix uses Kubernetes CRDs to create these resources, how all this is glued together is left to a Pipeline that is implemented as a container, where platform teams can use any tool that they need to wire things up together. 
```

2023-03-30 14:59 UTC, salaboy commented on daprblog/content/posts/2023/dapr-kratix/index.md
> +For this to work, the promise definition needs to include a reference to our **Environment CRD**, to the [Dapr]() and [Redis]() Promise coming from the Marketplace, and to a Pipeline that will glue t
done

2023-03-30 15:00 UTC, salaboy commented
@marcduiker I think I've fixed all your comments.. but can we delay this to Monday?

2023-04-03 13:19 UTC, marcduiker commented
Continued with #104

2023-04-03 13:19 UTC, closed without merging