Fix Dapr update info
dapr/blog pull request #112
Opened 2023-06-13 08:26 UTC by marcduiker

Specify 1.11.0 where needed and fix link.

2023-06-13 14:09 UTC, paulyuk requested changes
Please see comments

2023-06-13 14:09 UTC, paulyuk commented on daprblog/content/posts/2023/v1.11-release.md
>  Once you have installed the CLI, run:
Suggest we include a step to get the CLI.  We could point off to doc for this.

2023-06-13 14:09 UTC, paulyuk commented on daprblog/content/posts/2023/v1.11-release.md
Line 490 (not part of PR yet) suggest we strike "for RC releases like this".

2023-06-15 06:40 UTC, yaron2 approved these changes

2023-06-15 14:04 UTC, artursouza approved these changes

2023-06-15 14:37 UTC, hhunter-ms commented
@marcduiker for the blog repo, PRs only build successfully if created from dapr/blog, not from a fork of dapr/blog... try creating a branch on dapr/blog (not marcduiker/dapr-blog) and opening a new PR

2023-06-15 15:22 UTC, closed without merging